### ISSUE TITLE
Source code is missing

### ISSUE THREAD

**Issue by juliusliunz** [juliusliunz/messageToChiknrice#1]
Hi @chiknrice, this is Julius, do you still have the source code of pretty-log v0.8?

**Comment by chiknrice** [comment]
will try to find it and publish

**Comment by juliusliunz** [comment]
@chiknrice Hope you had a good long weekend. Any luck to find the source code? Cheers.

**Comment by chiknrice** [comment]
i found it, forgot to upload though.  will sure to upload later

**Comment by chiknrice** [comment]
already uploaded, unfortunately it's not 0.8 but i'm sure it's almost the same version as the one you have

**Comment by juliusliunz** [comment]
The version should be fine. Could you also include an Apache 2.0 license please? Thank you very much.

**Comment by chiknrice** [comment]
hi julius, i just had a quick read on the sources and i think it's outdated compared to what you have.  i would strongly suggest you just decompile the jar you have and copy the sources to be part of your utilities, you can remove my name and all references to me, you can also change the package names to conform to your project - you have my permission :)

**Comment by juliusliunz** [comment]
I'll take your suggestion. Thank you again for the permission and your time.
